spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/store-pandora
    username: postgres
    password: postgress
    driverClassName: org.postgresql.Driver